G0:
  accuracy:
    min: 0.85
    max: 1.0
G1:
  latency_ms:
    min: 0
    max: 200
G2:
  coverage:
    min: 0.9
    max: 1.0
G3:
  drift_score:
    min: 0.0
    max: 0.05
G4:
  precision:
    min: 0.8
    max: 1.0
G5:
  recall:
    min: 0.75
    max: 1.0
G6:
  robustness:
    min: 0.7
    max: 1.0
G7:
  report_integrity:
    min: 1
    max: 1
