[CmdletBinding()]
param(
  [string]$WFJsonPath,          # якщо не задано — беремо останній
  [string]$VerdictMdPath        # якщо є — додамо лінк на md-вердикт
)
Set-StrictMode -Version Latest

$root = Split-Path -Parent $PSCommandPath | Split-Path -Parent
$runs = Join-Path $root 'runs'
$repD = Join-Path $root ('reports\{0:yyyy-MM-dd}' -f (Get-Date))

function Find-LastWFJson {
  $wfJson = Get-ChildItem $runs -Recurse -Filter 'wf.results.json' -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime | Select-Object -Last 1
  if($wfJson){ return $wfJson.FullName } else { throw "wf.results.json not found under $runs" }
}

if(-not $WFJsonPath){ $WFJsonPath = Find-LastWFJson }
if(-not (Test-Path $WFJsonPath)){ throw "WF json not found: $WFJsonPath" }

# читаємо метадані WF
$meta = Get-Content $WFJsonPath -Raw | ConvertFrom-Json
$gridN = @($meta.Grid).Count
$wins  = @($meta.Windows).Count
$IS    = $meta.Aggregate.IS
$OOS   = $meta.Aggregate.Best
$BH    = $meta.Aggregate.BH

# Вердикт через наш чекер (робастний виклик)
$verPS = Join-Path $root 'scripts\Get-G5Verdict.ps1'
if(!(Test-Path $verPS)){ throw "Get-G5Verdict.ps1 missing: $verPS" }
$verPS = (Resolve-Path $verPS).Path; $ver = & $verPS -WFJsonPath $WFJsonPath

# спробуємо знайти артефакти поруч із JSON
$g5Dir = Split-Path $WFJsonPath -Parent
$csv   = Join-Path $g5Dir 'wf.oos.csv'
$csv   = if (Test-Path $csv) { $csv } else { $null }   # без окремого if

# знайти md-вердикт якщо не передали
if(-not $VerdictMdPath){
  $VerdictMdPath = (Get-ChildItem (Join-Path $root ('reports\{0:yyyy-MM-dd}' -f (Get-Date))) -Filter 'G5-Verdict-*.md' -ErrorAction SilentlyContinue |
                      Sort-Object LastWriteTime | Select-Object -Last 1).FullName
}

# збудуємо відносні шляхи
function Rel([string]$from,[string]$to){
  try{
    $u = New-Object System.Uri($from + (if(-not $from.EndsWith('\')){'\' } else {''}))
    $v = New-Object System.Uri($to)
    return [Uri]::UnescapeDataString($u.MakeRelativeUri($v).ToString()).Replace('/', '\')
  } catch { return $to }
}

New-Item -ItemType Directory -Path $repD -Force | Out-Null
$outHtml = Join-Path $repD ('G5-Report-{0:HHmmss}.html' -f (Get-Date))

$badge = if("$($ver.Verdict)" -eq 'ACCEPT'){ 'accept' } else { 'reject' }

# список «чому» (HTML-екранізація через System.Net.WebUtility)
$whyList = ($ver.Why | ForEach-Object { "<li>{0}</li>" -f [System.Net.WebUtility]::HtmlEncode($_) }) -join "`n"

$css = @"
body{font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Ubuntu;max-width:1000px;margin:32px auto;padding:0 16px;color:#0f172a;background:#ffffff}
h1{margin:0 0 12px 0} .muted{color:#64748b}
.badge{display:inline-block;padding:4px 10px;border-radius:12px;font-weight:600;font-size:14px}
.badge.accept{background:#dcfce7;color:#166534;border:1px solid #16a34a}
.badge.reject{background:#fee2e2;color:#991b1b;border:1px solid #ef4444}
.card{border:1px solid #e2e8f0;border-radius:12px;padding:14px 16px;margin:14px 0;box-shadow:0 1px 2px rgba(0,0,0,.03)}
table{border-collapse:collapse;width:100%} th,td{border:1px solid #e5e7eb;padding:8px 10px;text-align:left}
th{background:#f8fafc} code,a{color:#2563eb}
footer{margin-top:24px;color:#94a3b8;font-size:12px}
"@

function Row([string]$n,$m){ "<tr><td><b>$n</b></td><td>{0:N6}</td><td>{1:N3}</td><td>{2:N3}</td></tr>" -f $m.PnL,$m.Sharpe,$m.MaxDD }
$aggTable = @"
<table>
  <thead><tr><th>Set</th><th>PnL</th><th>Sharpe</th><th>MaxDD</th></tr></thead>
  <tbody>
    $(Row 'IS'  $IS)
    $(Row 'OOS' $OOS)
    $(Row 'BH'  $BH)
  </tbody>
</table>
"@

$relJson = Rel $outHtml $WFJsonPath
$relCsv  = if($csv){ Rel $outHtml $csv } else { $null }
$relMd   = if($VerdictMdPath){ Rel $outHtml $VerdictMdPath } else { $null }

$links = @()
$links += "<li>WF JSON: <a href=`"$relJson`">$relJson</a></li>"
if($relCsv){ $links += "<li>OOS CSV: <a href=`"$relCsv`">$relCsv</a></li>" }
if($relMd){  $links += "<li>Verdict (MD): <a href=`"$relMd`">$relMd</a></li>" }
$linksHtml = "<ul>`n" + ($links -join "`n") + "`n</ul>"

$srcEnc = [System.Net.WebUtility]::HtmlEncode($WFJsonPath)
$html = @"
<!doctype html>
<html lang="uk">
<meta charset="utf-8"/>
<title>G5 Report — $($ver.Verdict)</title>
<style>$css</style>
<body>
  <h1>G5 Report <span class="badge $badge">$($ver.Verdict)</span></h1>
  <div class="muted">Windows: <b>$wins</b> · Grid: <b>$gridN</b> · Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')</div>

  <div class="card">
    <h3 style="margin:0 0 8px 0">Чому та рішення</h3>
    <ul>
      $whyList
    </ul>
  </div>

  <div class="card">
    <h3 style="margin:0 0 8px 0">Агреговані метрики</h3>
    $aggTable
  </div>

  <div class="card">
    <h3 style="margin:0 0 8px 0">Артефакти</h3>
    $linksHtml
  </div>

  <footer>Generated by scripts/g5.report.ps1 · Source: $srcEnc</footer>
</body>
</html>
"@

$enc = New-Object System.Text.UTF8Encoding($false)
[IO.File]::WriteAllText($outHtml, $html, $enc)
Write-Host "[ok] G5 HTML report → $outHtml"