param()
$root = Split-Path -Parent $MyInvocation.MyCommand.Path | Split-Path -Parent
$inv  = Join-Path $root 'scripts\Invoke-G5WF.ps1'
$ver  = Join-Path $root 'scripts\Get-G5Verdict.ps1'
$repD = Join-Path $root ('reports\{0:yyyy-MM-dd}' -f (Get-Date))

# 1) якщо ще нема свіжого прогону — робимо demo WF
try { & $inv -WFProfile demo | Out-Null } catch { Write-Host "[warn] WF demo run skipped/failed: $_" }

# 2) Отримуємо вердикт і формуємо текст
$v   = & $ver
$why = ($v.Why | ForEach-Object { "- $_" }) -join "`n"    # <- окремо, без '+'

$md = @"
# G5 Verdict — $($v.Verdict)

**Дата:** $([DateTime]::Now.ToString('yyyy-MM-dd HH:mm:ss'))  
**Профілі:** (див. JSON у джерелі)  
**Джерело:** $($v.SourceJson)

## Результат
- Вердикт: **$($v.Verdict)**
- Чому:
$($why)

## Аггреговані метрики
- IS:  PnL=$([math]::Round($v.Summary.IS.PnL,6))  Sharpe=$([math]::Round($v.Summary.IS.Sharpe,3))  MaxDD=$([math]::Round($v.Summary.IS.MaxDD,3))
- OOS: PnL=$([math]::Round($v.Summary.OOS.PnL,6)) Sharpe=$([math]::Round($v.Summary.OOS.Sharpe,3)) MaxDD=$([math]::Round($v.Summary.OOS.MaxDD,3))
- BH:  PnL=$([math]::Round($v.Summary.BH.PnL,6))  Sharpe=$([math]::Round($v.Summary.BH.Sharpe,3))  MaxDD=$([math]::Round($v.Summary.BH.MaxDD,3))

---
Generated by scripts\g5.guard.selftest.ps1
"@

New-Item -ItemType Directory -Path $repD -Force | Out-Null
$outMd = Join-Path $repD ('G5-Verdict-{0:HHmmss}.md' -f (Get-Date))
$enc = New-Object System.Text.UTF8Encoding($false)
[IO.File]::WriteAllText($outMd, $md, $enc)
Write-Host "[selftest] Guard verdict: $($v.Verdict) → $outMd"