name: CI

on:
  push:
  pull_request:

jobs:
  tests-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Env diagnostics
        shell: pwsh
        run: |
          $PSVersionTable
          "PSModulePath:"
          ($env:PSModulePath -split ';') | ForEach-Object { "  - $_" }

      - name: Install Pester 5.5.0
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name Pester -Scope CurrentUser -Force -SkipPublisherCheck -RequiredVersion 5.5.0
          Get-Module -ListAvailable Pester | Sort-Object Version -Descending | Select-Object -First 3 | Format-Table Name,Version,ModuleBase

      - name: Run tests (Pester v5, tests/ci only)
        shell: pwsh
        env:
          ATS_NOEXIT: "1"
        run: |
          $ErrorActionPreference = 'Stop'
          Get-Module Pester | Remove-Module -Force -ErrorAction SilentlyContinue
          Import-Module Pester -RequiredVersion 5.5.0 -Force
          Invoke-Pester -CI -Path tests/ci
