name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare (folders + diag)
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force
          $PSVersionTable
          Write-Host "Pester modules available:"
          Get-Module -ListAvailable Pester | Select-Object Name,Version,Path | Format-Table -AutoSize | Out-String | Write-Host
          New-Item -ItemType Directory -Force -Path reports | Out-Null
          New-Item -ItemType Directory -Force -Path data\processed | Out-Null

      - name: Run tests (Windows PowerShell + Pester v3)
        run: |
          Push-Location tests
          try {
            Invoke-Pester -EnableExit
          } finally {
            Pop-Location
          }

      - name: Upload artifacts (reports, gates, processed)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ats-reports
          path: |
            reports/**
            docs/gates.md
            data/processed/**
          if-no-files-found: warn
