name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh   # PowerShell 7
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare folders
        run: |
          New-Item -ItemType Directory -Force -Path reports | Out-Null
          New-Item -ItemType Directory -Force -Path data/processed | Out-Null

      - name: Install Pester 5
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Pester -Scope CurrentUser -Force -SkipPublisherCheck
          Import-Module Pester -Force
          Write-Host "Using Pester:" (Get-Module Pester).Version

      - name: Run tests (Pester 5)
        run: |
          $conf = New-PesterConfiguration
          $conf.Run.Path = 'tests'
          $conf.Output.Verbosity = 'Detailed'
          $conf.TestResult.Enabled = $true
          $conf.TestResult.OutputPath = 'reports/pester-results.xml'
          Invoke-Pester -Configuration $conf

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ats-reports
          path: |
            reports/**
            docs/gates.md
            data/processed/**
          if-no-files-found: warn
