name: G2 Smoke

on:
  workflow_dispatch:
  push:
    paths:
      - 'run.ps1'
      - 'scripts/**'
      - 'config/**'
      - '.github/workflows/g2-smoke.yml'

jobs:
  g2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run G2 smoke
        shell: pwsh
        run: |
          .\run.ps1 -Gate G2
      - name: Upload report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: g2-report
          path: reports/**
